services:
  ttnet:
    image: ttnet
    build: .
    container_name: ttnet
    #deploy:
    #  resources:
    #    reservations:
    #      devices:
    #        - capabilities: [gpu]
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
    #volumes:
    #  - /workspaces/ttnet-docker/ttnet:/ttnet
    ports:
      - "6006:6006"    
    
    #command: ["python", "main.py"]